site_name: Bloomier Filter in the Python Programming Language
theme: readthedocs
repo_url: https://github.com/prosseek/BloomierFilterPython
extra_javascript:
  - extra.js
extra_css:
  - extra.css
pages:
  - Home: index.md
markdown_extensions:
    - admonition:
